export const OPEN_LOGIN = "OPEN_LOGIN"
export const OPEN_REGISTER = "REGISTER_LOGIN"

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const AUTH_LOADING = 'AUTH_LOADING'
export const USER_LOADING = 'USER_LOADING'

export const REGISTER_PEMBELI_SUCCESS = "REGISTER_PEMBELI_SUCCESS"
export const REGISTER_PEMBELI_ERROR = 'REGISTER_PEMBELI_ERROR'

export const REGISTER_TOKO_SUCCESS = "REGISTER_TOKO_SUCCESS"
export const REGISTER_TOKO_ERROR = 'REGISTER_TOKO_ERROR'
